// src/components/PageSkeleton.vue
<template>
  <div
    class="
      min-h-screen
      bg-gradient-to-br
      from-yellow-500
      via-red-400
      to-pink-600
      pt-2
      lg:px-4
      lg:py-16
      dark:from-violet-900
      dark:via-indigo-900
      dark:to-blue-gray-900
    "
  >
    <div
      class="
        bg-white
        dark:bg-gray-800
        max-w-6xl
        mb-4
        lg:mx-auto
        lg:shadow-xl
        py-2
        px-4
        lg:px-16
        lg:py-12
        lg:rounded-3xl
      "
    >
      <header class="mb-4 flex justify-center md:justify-end">
        <Nav />
      </header>
      <main>
        <slot />
      </main>
    </div>
    <footer class="max-w-6xl mx-auto">
      <Footer />
    </footer>
  </div>
</template>

<script>
export default {
  name: 'PageSkeleton',
}
</script>

<style>
@font-face {
  font-family: 'Rubik';
  font-weight: 400;
  src: local('Rubik'),
    url(@/static/fonts/Rubik/Rubik-Regular.ttf) format('truetype');
}

@font-face {
  font-family: 'Rubik';
  font-weight: 700;
  src: local('Rubik'),
    url(@/static/fonts/Rubik/Rubik-Bold.ttf) format('truetype');
}

html {
  font-family: 'Rubik';
}
</style>

// app/components/PageSkeleton.tsx
import Footer from "./Footer";
import Navigation from "./Navigation";

export default function PageSkeleton({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen overflow-hidden bg-gradient-to-br from-yellow-500 via-red-400 to-pink-600 pt-2 dark:from-violet-900 dark:via-indigo-900 dark:to-slate-900 md:px-4 md:py-16">
      <div className="mb-4 max-w-6xl bg-white py-2 px-4 dark:bg-gray-800 md:mx-auto md:rounded-3xl md:px-16 md:py-12 md:shadow-2xl">
        <header className="mb-4 flex justify-end">
          <Navigation />
        </header>
        <main className="mb-8">{children}</main>
      </div>
      <footer className="mx-auto max-w-6xl">
        <Footer />
      </footer>
    </div>
  );
}
